packages:
        - apps/*
        - packages/*
onlyBuiltDependencies:
        - "@prisma/client"
        - "@prisma/engines"
        - "@sentry/cli"
        - esbuild
        - prisma
        - protobufjs
        - sharp
